env:
  TERM: xterm-256color

colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    # background: '#282828'
    soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

font:
  normal:
    family: Menlo
  size: 22

key_bindings:
  - { key: Left,   mods: Alt,  chars: "\x1bb" } # one word left
  - { key: Right,  mods: Alt,  chars: "\x1bf" } # one word right
  - { key: F,      mods: Alt,  chars: "\x1bf" } # one word left
  - { key: B,      mods: Alt,  chars: "\x1bb" } # one word right

