env:
  TERM: xterm-256color

colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    # background: '#282828'
    soft contrast: background = '#32302f'
    foreground: '#ebdbb2'


font:
  normal:
    family: FantasqueSansMono
  size: 28
